export const refs = {
  gallery: document.querySelector('.gallery'),
  genresList: document.querySelector('.genres__list'),
  // switchBtn: document.querySelector('.switch-btn'),
  // switchBtnToggle: document.querySelector('.switch-btn::after'),
  body: document.querySelector('body'),
  card: document.querySelector('.gallery__card'),
  header: document.querySelector('.header'),
  pageHome: document.querySelector('#home'),
  pageLibrary: document.querySelector('#library'),
  form: document.querySelector('.header__wrap--form'),
  btnLibrary: document.querySelector('.header__wrap--btn'),
  headerWrap: document.querySelector('.header__wrap'),
  switchBtn: document.querySelector('.switch-btn'),
  darkBtn: document.querySelector('.switch-btn__icon--dark'),
  lightBtn: document.querySelector('.switch-btn__icon--light'),
  subtitle: document.querySelectorAll('.gallery__subtitle'),
  cards: document.querySelectorAll('.gallery__card'),
};
